### ISSUE TITLE
throw new InitializationError()

### ISSUE THREAD

**Issue by mehmetkose** [smildlzj/gulp-prepack#1]
I think it's related with https://github.com/facebook/prepack/issues/590

![ekran resmi 2017-05-10 15 42 31](https://cloud.githubusercontent.com/assets/706678/25899133/60059e1e-3597-11e7-87d9-22abfc21068e.png)

**Comment by smildlzj** [comment]
```
var buffer = require('vinyl-buffer');
...

instanceBrowserify
  .bundle()
  .pipe(source('app.js')) 
  .pipe(buffer())
  .pipe(prepack())
  .pipe(gulp.dest('dist'));
```

you may code it like that

**Comment by mehmetkose** [comment]
uh, I updated whole things but I will try. sorry.

**Comment by smildlzj** [comment]
please call buffer() first when you call prepack().  source -> buffer -> prepack

**Comment by mehmetkose** [comment]
can you share an working gulpfile?  It doesn't work for me :(
![ekran resmi 2017-05-10 18 28 30](https://cloud.githubusercontent.com/assets/706678/25906874/828b7f32-35ae-11e7-89c7-29f91929f349.png)

**Comment by smildlzj** [comment]
```
gulp.task('default', function () {
  return browserify({
    entries: ['./src/index.js'],
    extensions: ['.js']
  })
  .bundle()
  .pipe(source('bundle.js')) 
  .pipe(buffer())
  .pipe(prepack())
  .pipe(gulp.dest('./dist'));
});
```

if you using gulp.src , just like this is work
```
gulp.src('./src/*.js')
  .pipe(prepack())
  .pipe(gulp.dest('./dist'));
});

```

**Comment by mehmetkose** [comment]
dude, I tried second time. but still same problem here. What am I missing? 
can you share basic gulp "project" for this? gist or something
